var data =[
  {"id":"a0","name":"aa","label":"P2P下载","children":[
      {"id":"a1","name":"dd","label":"BitTorrent","children":[
        {"id":"a20","name":"dd20","label":"三级","children":[
          {"id":"a21","name":"dd21","label":"四级","children":[]}
        ]},
        {"id":"a22","name":"dd20","label":"三级1","children":[
          {"id":"a23","name":"dd21","label":"四级","children":[]}
        ]}
      ]},
      {"id":"a2","name":"dd1","label":"eMule(电螺)","children":[]},
      {"id":"a3","name":"dd2","label":"DirectConnect","children":[]},
      {"id":"a4","name":"dd3","label":"Gnutella","children":[]},
      {"id":"a5","name":"dd4","label":"KaZaa","children":[]},
      {"id":"a6","name":"dd5","label":"Poco(宝酷) ","children":[]},
      {"id":"a7","name":"dd1","label":"Thunder迅雷","children":[]},
      {"id":"a08","name":"dd2","label":"Kugoo(酷狗)","children":[]},
      {"id":"a09","name":"dd3","label":"Vagaa(哇嘎)","children":[]},
      {"id":"a10","name":"dd4","label":"FlashGet(快车)","children":[]},
      {"id":"a11","name":"dd5","label":"TuoTu(脱兔)","children":[]},
      {"id":"a12","name":"dd1","label":"PPGou(屁屁狗)","children":[]},
      {"id":"a13","name":"dd2","label":"QQ旋风下载","children":[]},
      {"id":"a14","name":"dd3","label":"酷我音乐盒","children":[]},
      {"id":"a15","name":"dd4","label":"千千静听","children":[]},
      {"id":"a16","name":"dd5","label":"QQ音乐","children":[]},
      {"id":"a17","name":"dd1","label":"谷歌音乐盒","children":[]},
      {"id":"a18","name":"dd2","label":"360软件管家","children":[]},
      {"id":"a19","name":"dd3","label":"多米音乐","children":[]}
    ]},
  {"id":"b0","name":"bb","label":"P2P流媒体","children":[
      {"id":"b01","name":"hh1","label":"PPTV网络电视","children":[]},
      {"id":"b02","name":"hh1","label":"PPS影音","children":[]},
      {"id":"b03","name":"hh2","label":"QQLive网络电视","children":[]},
      {"id":"b04","name":"hh3","label":"沸点网络电视","children":[]},
      {"id":"b05","name":"hh4","label":"UUSee网络电视","children":[]},
      {"id":"b06","name":"hh5","label":"TVAnts","children":[]},
      {"id":"b07","name":"hh1","label":"TvKoo","children":[]},
      {"id":"b08","name":"hh1","label":"QVOD快播影视","children":[]},
      {"id":"b09","name":"hh2","label":"风行","children":[]},
      {"id":"b10","name":"hh3","label":"皮皮高清","children":[]},
      {"id":"b11","name":"hh4","label":"迅雷看看","children":[]}
    ]},
  {"id":"c0","name":"cc","label":"流媒体","children":[
      {"id":"c01","name":"hh1","label":"新浪视频","children":[]},
      {"id":"c02","name":"hh1","label":"CNTV","children":[]},
      {"id":"c03","name":"hh1","label":"RTSP流媒体","children":[]},
      {"id":"c04","name":"hh1","label":"MMS流媒体","children":[]},
      {"id":"c05","name":"hh1","label":"VideoRTP","children":[]},
      {"id":"c06","name":"hh1","label":"网页视频","children":[]},
      {"id":"c07","name":"hh1","label":"Flash视频","children":[]},
      {"id":"c08","name":"hh1","label":"YouTube视频","children":[]},
      {"id":"c09","name":"hh1","label":"土豆网","children":[]},
      {"id":"c10","name":"hh1","label":"优酷网","children":[]},
      {"id":"c11","name":"hh1","label":"酷6网 ","children":[]},
      {"id":"c12","name":"hh1","label":"56视频","children":[]},
      {"id":"c13","name":"hh1","label":"MediaPlay","children":[]},
      {"id":"c14","name":"hh1","label":"RealPlay","children":[]},
      {"id":"c15","name":"hh1","label":"QuickTime ","children":[]},
      {"id":"c16","name":"hh1","label":"乐视网络电视","children":[]},
      {"id":"c17","name":"hh1","label":"网易视频","children":[]},
      {"id":"c18","name":"hh1","label":"优米网","children":[]},
      {"id":"c19","name":"hh1","label":"东方宽频","children":[]},
      {"id":"c20","name":"hh1","label":"手机电视Dopool","children":[]},
      {"id":"c21","name":"hh1","label":"暴风影音","children":[]},
      {"id":"c22","name":"hh1","label":"奇艺影音","children":[]},
      {"id":"c23","name":"hh1","label":"搜狐影音","children":[]},
      {"id":"c24","name":"hh1","label":"凤凰视频","children":[]},
      {"id":"c25","name":"hh1","label":"SopCast ","children":[]},
      {"id":"c26","name":"hh1","label":"芒果TV","children":[]},
      {"id":"c27","name":"hh1","label":"电影网播放器","children":[]},
      {"id":"c28","name":"hh1","label":"百度影音","children":[]},
      {"id":"c29","name":"hh1","label":"腾讯视频","children":[]},
      {"id":"c30","name":"hh1","label":"豆瓣FM","children":[]},
      {"id":"c31","name":"hh1","label":"风云直播","children":[]},
      {"id":"c32","name":"hh1","label":"懒人听书","children":[]},
      {"id":"c33","name":"hh1","label":"凤凰电台","children":[]},
      {"id":"c34","name":"hh1","label":"唱吧","children":[]},
      {"id":"c35","name":"hh1","label":"爱唱","children":[]},
      {"id":"c36","name":"hh1","label":"K歌达人 ","children":[]},
      {"id":"c37","name":"hh1","label":"巨鲸音乐","children":[]},
      {"id":"c38","name":"hh1","label":"一听音乐","children":[]},
      {"id":"c39","name":"hh1","label":"虾米音乐","children":[]},
      {"id":"c40","name":"hh1","label":"九酷音乐","children":[]},
      {"id":"c41","name":"hh1","label":"DJ音乐","children":[]},
      {"id":"c42","name":"hh1","label":"搜狗音乐","children":[]},
      {"id":"c43","name":"hh1","label":"微看电视","children":[]},
      {"id":"c44","name":"hh1","label":"WTV手机电视 ","children":[]},
      {"id":"c45","name":"hh1","label":"EasyTV手机电视","children":[]},
      {"id":"c46","name":"hh1","label":"魔力高清影视","children":[]},
      {"id":"c47","name":"hh1","label":"喜马拉雅电台","children":[]},
      {"id":"c48","name":"hh1","label":"快手看片","children":[]},
      {"id":"c49","name":"hh1","label":"网易云音乐","children":[]},
      {"id":"c50","name":"hh1","label":"音乐雷达","children":[]},
      {"id":"c51","name":"hh1","label":"soundhound","children":[]},
      {"id":"c52","name":"hh1","label":"你听","children":[]},
      {"id":"c53","name":"hh1","label":"咪咕音乐","children":[]},
      {"id":"c54","name":"hh1","label":"其他TCP视频 ","children":[]},
      {"id":"c55","name":"hh1","label":"其他UDP视频 ","children":[]},
      {"id":"c56","name":"hh1","label":"手机视频","children":[]}
  ]},
  {"id":"d0","name":"ee","label":"浏览","children":[
      {"id":"d01","name":"hh1","label":"HTTP网页浏览","children":[]},
      {"id":"d02","name":"hh1","label":"HTTPS ","children":[]},
      {"id":"d03","name":"hh1","label":"HTTPProxy ","children":[]},
      {"id":"d04","name":"hh1","label":"Windows升级 ","children":[]},
      {"id":"d05","name":"hh1","label":"彩信","children":[]},
      {"id":"d06","name":"hh1","label":"WAP ","children":[]},
      {"id":"d07","name":"hh1","label":"新浪微博","children":[]},
      {"id":"d08","name":"hh1","label":"腾讯微博","children":[]},
      {"id":"d09","name":"hh1","label":"搜狐微博","children":[]},
      {"id":"d10","name":"hh1","label":"网易微博","children":[]},
      {"id":"d11","name":"hh1","label":"人人网","children":[]},
      {"id":"d12","name":"hh1","label":"开心网","children":[]},
      {"id":"d13","name":"hh1","label":"大众点评","children":[]},
      {"id":"d14","name":"hh1","label":"书旗免费小说","children":[]},
      {"id":"d15","name":"hh1","label":"iReader ","children":[]},
      {"id":"d16","name":"hh1","label":"QQ阅读","children":[]},
      {"id":"d17","name":"hh1","label":"扎客","children":[]},
      {"id":"d18","name":"hh1","label":"VIVA","children":[]},
      {"id":"d19","name":"hh1","label":"糗事百科","children":[]},
      {"id":"d20","name":"hh1","label":"爱看动漫","children":[]},
      {"id":"d21","name":"hh1","label":"微云","children":[]},
      {"id":"d22","name":"hh1","label":"百度云","children":[]},
      {"id":"d23","name":"hh1","label":"QQ同步助手","children":[]},
      {"id":"d24","name":"hh1","label":"金山快盘","children":[]},
      {"id":"d25","name":"hh1","label":"墨迹天气","children":[]},
      {"id":"d26","name":"hh1","label":"360云盘 ","children":[]},
      {"id":"d27","name":"hh1","label":"百度云记事本","children":[]},
      {"id":"d28","name":"hh1","label":"新浪微盘","children":[]},
      {"id":"d29","name":"hh1","label":"我查查","children":[]},
      {"id":"d30","name":"hh1","label":"快拍二维码","children":[]},
      {"id":"d31","name":"hh1","label":"谷歌地球","children":[]},
      {"id":"d32","name":"hh1","label":"凯立德地图","children":[]},
      {"id":"d33","name":"hh1","label":"高德地图","children":[]},
      {"id":"d34","name":"hh1","label":"谷歌地图","children":[]},
      {"id":"d35","name":"hh1","label":"街旁","children":[]},
      {"id":"d36","name":"hh1","label":"QQ空间","children":[]},
      {"id":"d37","name":"hh1","label":"UCWEB浏览器 ","children":[]},
      {"id":"d38","name":"hh1","label":"UC首页登录","children":[]},
      {"id":"d39","name":"hh1","label":"百度搜索","children":[]},
      {"id":"d40","name":"hh1","label":"移动微博","children":[]},
      {"id":"d41","name":"hh1","label":"手机动漫","children":[]},
      {"id":"d42","name":"hh1","label":"手机冲浪","children":[]},
      {"id":"d43","name":"hh1","label":"手机报","children":[]},
      {"id":"d44","name":"hh1","label":"快讯","children":[]},
      {"id":"d45","name":"hh1","label":"手机阅读","children":[]}
  ]},
  {"id":"e0","name":"gg","label":"下载","children":[]},
  {"id":"f0","name":"cc","label":"电子邮件","children":[]},
  {"id":"g0","name":"ee","label":"即时通信","children":[]},
  {"id":"h0","name":"gg","label":"游戏娱乐","children":[]},
  {"id":"i0","name":"cc","label":"电子商务","children":[]},
  {"id":"j0","name":"ee","label":"网络电话","children":[]},
  {"id":"k0","name":"gg","label":"路由和网管","children":[]},
  {"id":"l0","name":"cc","label":"病毒和攻击","children":[]},
  {"id":"m0","name":"ee","label":"用户自定义","children":[]},
  {"id":"n0","name":"gg","label":"Generic TCP","children":[]},
  {"id":"o0","name":"cc","label":"Generic UDP","children":[]}
]
